const contactIdCodes = [
  { code: '070', zone: 'TEST', eventType: 'Unknown', class: 'Test/Misc.', description: 'Test-Restore' },
  { code: '076', zone: 'TEST', eventType: 'Unknown', class: 'Test/Misc.', description: 'Test - Cell Backup' },
  { code: '100', zone: 'MEDICAL', eventType: 'Zone', class: 'Medical', description: 'Medical' },
  { code: '101', zone: 'MEDICAL', eventType: 'Zone', class: 'Medical', description: 'PENDANT TRANSMITTER' },
  { code: '102', zone: 'MEDICAL', eventType: 'Zone', class: 'Medical', description: 'Medical' },
  { code: '103', zone: 'TECHNICIAN', eventType: 'Unknown', class: 'Test/Misc.', description: 'UNDEFINED DSC CONTACT ID CODE' },
  { code: '104', zone: 'RESTORE', eventType: 'Zone', class: 'Test/Misc.', description: 'DSC CID RESTORE' },
  { code: '105', zone: 'TECHNICIAN', eventType: 'Unknown', class: 'Test/Misc.', description: 'UNDEFINED DSC CONTACT ID CODE' },
  { code: '106', zone: 'ABORT', eventType: 'User', class: 'General Alarms', description: '' },
  { code: '109', zone: 'TROUBLE', eventType: 'Zone', class: 'System Troubles', description: 'Tamper' },
  { code: '110', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: '' },
  { code: '111', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'SMOKE' },
  { code: '112', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'COMBUSTION' },
  { code: '113', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'WATER FLOW' },
  { code: '114', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'HEAT' },
  { code: '115', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'PULL STATION' },
  { code: '116', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'DUCT' },
  { code: '117', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'FLAME' },
  { code: '118', zone: 'FIRE', eventType: 'Zone', class: 'Fire Alarms', description: 'NEAR ALARM' },
  { code: '11F', zone: 'TECHNICIAN', eventType: 'Unknown', class: 'Test/Misc.', description: 'UNDEFINED DSC CONTACT ID CODE' },
  { code: '120', zone: 'PANIC(audible)', eventType: 'Zone', class: 'Panic Alarms', description: 'AUDIBLE' },
  { code: '121', zone: 'DURESS', eventType: 'Zone', class: 'Panic Alarms', description: '' },
  { code: '122', zone: 'DURESS', eventType: 'Zone', class: 'Panic Alarms', description: 'SILENT' },
  { code: '123', zone: 'PANIC(audible)', eventType: 'Zone', class: 'Panic Alarms', description: 'AUDIBLE' },
  { code: '124', zone: 'DURESS', eventType: 'User', class: 'Panic Alarms', description: 'Silent' },
  { code: '125', zone: 'DURESS', eventType: 'User', class: 'Panic Alarms', description: 'Silent' },
  { code: '130', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: '' },
  { code: '131', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'PERIMETER' },
  { code: '132', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'INTERIOR' },
  { code: '133', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: '24 HOUR' },
  { code: '134', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'ENTRY/EXIT' },
  { code: '135', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'DAY/NIGHT' },
  { code: '136', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'OUTDOOR' },
  { code: '137', zone: 'TAMPER', eventType: 'Zone', class: 'Burglar Alarms', description: 'TAMPER' },
  { code: '138', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: 'NEAR ALARM' },
  { code: '139', zone: 'BURG', eventType: 'Zone', class: 'Burglar Alarms', description: '' },
  { code: '13E', zone: 'TECHNICIAN', eventType: 'Unknown', class: 'Test/Misc.', description: 'UNDEFINED DSC CONTACT ID CODE' },
  { code: '140', zone: 'ALARM', eventType: 'Zone', class: 'General Alarms', description: '' },
  { code: '141', zone: 'ALARM', eventType: 'Zone', class: 'General Alarms', description: 'POLLING LOOP OPEN' },
  { code: '142', zone: 'TROUBLE', eventType: 'Zone', class: 'General Alarms', description: 'POLLING LOOP SHORT' },
  { code: '143', zone: 'TROUBLE', eventType: 'Zone', class: 'General Alarms', description: 'EXP MODULE FAILURE' },
  { code: '144', zone: 'TAMPER', eventType: 'Zone', class: 'General Alarms', description: 'SENSOR TAMPER' },
  { code: '145', zone: 'TAMPER', eventType: 'Zone', class: 'General Alarms', description: 'EXP MODULE TAMPER' },
  { code: '145', zone: '906', eventType: 'TECHNICIAN', class: 'System Troubles', description: 'AES IP-Link Door Tamper' },
  { code: '146', zone: 'BURG', eventType: 'Zone', class: 'General Alarms', description: 'SILENT' },
  { code: '150', zone: 'ALARM', eventType: 'Zone', class: 'General Alarms', description: '' },
  { code: '151', zone: 'ALARM', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'GAS DETECTED' },
  { code: '152', zone: 'TROUBLE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'REFRIGERATION' },
  { code: '153', zone: 'TROUBLE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'LOSS OF HEAT' },
  { code: '154', zone: 'TROUBLE', eventType: 'Zone', class: '', description: 'WATER LEAKAGE' },
  { code: '155', zone: 'ALARM', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'FOIL BREAK' },
  { code: '156', zone: 'ALARM', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'DAY TROUBLE' },
  { code: '157', zone: 'TROUBLE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'LOW BOTTLED GAS LVL' },
  { code: '158', zone: 'TEMPERATURE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'HIGH TEMP' },
  { code: '159', zone: 'TEMPERATURE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'LOW TEMP' },
  { code: '161', zone: 'ALARM', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'LOSS OF AIR FLOW' },
  { code: '162', zone: 'ALARM', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'CARBON MONOXIDE DETECTED' },
  { code: '163', zone: 'TROUBLE', eventType: 'Zone', class: '24 Hour Non-Burglary', description: 'TANK LEVEL' },
  { code: '199', zone: 'ABORT', eventType: 'User', class: 'Open/Close', description: 'After alarm open' },
  { code: '200', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'FIRE SUPERVISORY' },
  { code: '201', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'LOW WATER PRESSURE' },
  { code: '202', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'LOW CO2' },
  { code: '203', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: '' },
  { code: '204', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'LOW WATER LEVEL' },
  { code: '205', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'PUMP ACTIVATED' },
  { code: '206', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'PUMP FAILURE' },
  { code: '210', zone: 'SUPERVISORY', eventType: 'Zone', class: 'Fire Supervisory', description: 'Supervisory' },
  { code: '213', zone: 'TROUBLE', eventType: 'Zone', class: '', description: 'SPRINKLER TROUBLE' },
]
export default contactIdCodes